blank_issues_enabled: false
contact_links:
  - name: LnFTI Jira Board
    url: https://chirax.atlassian.net/jira/software/projects/LNFTI/boards/67
    about: Gunakan Jira sebagai single source of truth untuk task, story, bug, dan spike.
